Added the ability to assign the computer's local hostname to id and get the computer's local ip address
macsnoeren/python-p2p-network pull request #17
Opened 2021-04-12 14:58 UTC by rdash99

Examples have been created to demonstrate - however, as node.py needs to be modified to accept ID as an attribute I have placed the modified copy in the examples folder as the unmodified package is currently used by default if the import references p2pnetwork.node.

I decided to make these minor changes and contribute this as I needed the ability to assign an ID as well as automatically assign a local IP to a node, and although the ID may not always be unique, it should serve well enough to identify a locally networked machine in a human-readable manner which is potentially useful when built into an application with a GUI interface.

I hope this is useful to someone in the future.

2021-04-28 19:10 UTC, macsnoeren commented
I will check it shortly :).

2021-05-13 11:15 UTC, cgsops commented
is this can run behind nat?

2021-06-08 11:22 UTC, macsnoeren commented
Note that this is a framework offcourse, so you can implement a peer-to-peer application. The id of the nodes are self generated, see node.py (line 62-65). Furthermore, the nodeconnection.py holds a key-value data store to store meta information about the node, that can be a local IP for instance. This can be accessed using:

'''python
def set_info(self, key, value):        self.info[key] = value
def get_info(self, key):        return self.info[key
'''

Is this already good for you? 

However, I can imagine that it is very nice when it is possible to set the ID of the node yourself. For example when it is constructed. The datastore can be used to store the local IP and other information. I would like to follow this approach. Is that okay for you?

2021-06-08 11:53 UTC, macsnoeren requested changes
Check my comments ;)

2021-06-08 11:53 UTC, macsnoeren commented on examples/my_own_p2p_application hostname example.py
> +
De nodes need to have unique ID's.

2021-06-08 11:53 UTC, macsnoeren commented on examples/node.py
> +        """Create instance of a Node. If you want to implement the Node functionality with a callback, you should
You can modify the real class. Why did you create a new file?

2021-06-08 11:53 UTC, macsnoeren commented on examples/node.py
> +    def __init__(self, host, port, id, callback=None):
When the id is not used, we could fall back on the automatic generation of the id as we had. Is that okay?

2021-06-08 16:52 UTC, SamuelHaidu commented
I think that we need to remove the id handshake in the base node class. This functionality need to be implemented by programmer because is in the level of aplication not in the level of network. This can be implemented in a child class like the examples.

2021-06-09 21:22 UTC, macsnoeren commented
I agree, so what I proposed is okay to implement? for testing purposes, the generated id would be okay to put in. However, I agree to the fact the the application should deal with this: Only unique ID's should exist in the network. Could you provide some answers to my questions? Thanks!

2021-06-09 21:33 UTC, macsnoeren commented
> is this can run behind nat?

Yes and no. A node is able to recieve connections from other nodes and make connections to other nodes. That is the principle of a peer-to-peer network. So, it cannot run behind nat. However, when you have a node that only needs to connect to another node(s) (some kind of leaf node), you can run it behind a nat. So you alway need nodes that are accessible.

2021-06-11 21:10 UTC, SamuelHaidu commented
> I agree, so what I proposed is okay to implement? for testing purposes, the generated id would be okay to put in. However, I agree to the fact the the application should deal with this: Only unique ID's should exist in the network. Could you provide some answers to my questions? Thanks!

Yes, is a good idea that every node has a unique ID (may be change the 512 bits hash to UUID, what you think?) but only locally. Check lines 216/217 that node exchange over network your ids. This implies that a application implemented with this framework has a little protocol. I think that in this moment the id is not useful to send messages. The id is only a attribute in NodeConnection object. I think the changes you made to the code don't change much in practice.

2021-06-16 00:37 UTC, macsnoeren commented
I will check the UUID. It is a good idea.

2021-06-16 00:43 UTC, merged