Events when a connection error occurs and a lot of refactoring
macsnoeren/python-p2p-network pull request #26
Opened 2021-12-27 01:04 UTC by SamuelHaidu

### New feature:
#### Solved the TODO: "Also create events when things go wrong, like a connection with a node has failed."

Created two methods on Node class: `Node.outbound_node_connection_error()` and `Node.inbound_node_connection_error()`
the two are invoked when occurs a error on `Node.connect_with_node()` or `Node.run()`
The methods receive as a parameter a Exception object.

### Minor changes:
#### Removed unnecessary comments

Some comments are redundant like email, and author, version (not updated). Everything is in `setup.py` or `__author__` `__version__` module attributes.

#### Docstrings adhering to the PEP 275 convention

Some docstrings is located in non conventional places. Module docstrings is on top. Removed docstrings from class constructor  and put on class top. Some documentations redundancies are removed. Its help the IDEs to find the documentation,

####  Spacings and other thing adhering PEP 8 convention

Add spaces and break lines. Replace `== None ` comparison to `is None`

#### Adds annotation in all methods

Adds python annotations in all methods. Its help the IDEs show autocomplete  and code errors, besides making it more documented.

#### Replace legacy string formatting

Replaced the legacy python 2 `%` , `str.format()` or string concatenation to modern fstrings. Too much more readable.

#### Refactoring methods

`Node.send_to_nodes()` KISS using filter and `self.all_nodes` attribute

`Node.send_to_node()` KISS using addition assignment and `self.all_nodes` attribute

`Node.connect_with_node` A bug was fixed using a loop to check if every inbound nodes has the same host or id. 

##### This has been simplified by
**Before connection**
Check if every connected node (inbound or outbound) has the same host or port.

**After the connection**
Check if every node  (inbound or outbound) has the same ID

Now the checks types are separated.

2022-01-06 20:28 UTC, macsnoeren commented
Wow! I will have a look in the coming weeks. Happy new year and thanks for the contribution!

2022-01-08 18:23 UTC, SamuelHaidu commented
Thanks, happy new year!!  I'm preparing more commits hehehe

2022-02-02 13:27 UTC, macsnoeren requested changes
Could you check how to fix the bug as mentioned in the review?

2022-02-02 13:27 UTC, macsnoeren commented on p2pnetwork/node.py
> -            # Fix bug: Cannot connect with nodes that are already connected with us!
This bug has not been resolved by the code above. Inbound connections cannot be checked by their port. We should check for a similar node id to check if we are already connected to the node.

2022-04-16 23:00 UTC, macsnoeren commented
@SamuelHaidu Can you help me with this?

2022-04-21 22:23 UTC, macsnoeren commented
I have made some changed to development. Most probably you need to fetch development to be able to provide the required changes.

2022-04-26 17:32 UTC, SamuelHaidu commented
Sorry maybe you can't see my review :(

Unintentionally I add this verification on the line 155:

`171 if self.id == connected_node_id:`
to:
`155 if self.id == connected_node_id or connected_node_id in node_ids:`

A doubt: Check by ip and port can be removed? Can be seen as redundant

2022-04-26 22:17 UTC, macsnoeren approved these changes
I have made the required changes.

2022-04-26 22:17 UTC, merged